-include("gen_fun.hrl").
-gen_fun(#{remote => applicative, functions => [pure/1, '<*>'/2, lift_a2/3, '<*'/2, '*>'/2]}).
-gen_fun(#{remote => applicative, functions => [pure/2, '<*>'/3, lift_a2/4, '<*'/3, '*>'/3]}).
