-compile({parse_transform, overload_op}).
-overloads([{functor, ['<$>', '<$']}, {applicative, ['<*>', '*>', '<*']}]).
-overloads([{monad, ['>>=', '>>']}, {alternative, ['<|>']}]).
-overloads([{function_instance, ['.']}]).
